[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Taylor Sutton <tsutton125@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
aoc-runner  = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.4.2"
